plugins {
    id 'java'
    id 'application'
    id 'com.gradleup.shadow' version '9.5.1'
}

java {
    sourceCompatibility = JavaVersion.VERSION_25
    targetCompatibility = JavaVersion.VERSION_25
}

repositories {
    mavenCentral()
}

dependencies {
    String javaFxVersion = '17.0.7'
    String osName = System.getProperty('os.name').toLowerCase()
    String macPlatform = System.getProperty('os.arch') in ['aarch64', 'arm64']
            ? 'mac-aarch64' : 'mac'
    def javafxPlatforms = [macPlatform, 'win', 'linux']

    if (osName.contains('win')) {
        javafxPlatforms = ['win', 'mac', 'linux']
    } else if (osName.contains('linux')) {
        javafxPlatforms = ['linux', 'mac', 'win']
    }

    javafxPlatforms.each { platform ->
        implementation("org.openjfx:javafx-base:${javaFxVersion}:${platform}")
        implementation("org.openjfx:javafx-controls:${javaFxVersion}:${platform}")
        implementation("org.openjfx:javafx-fxml:${javaFxVersion}:${platform}")
        implementation("org.openjfx:javafx-graphics:${javaFxVersion}:${platform}")
    }
}

application {
    mainClass.set("javafxtutorial.Launcher")
    applicationDefaultJvmArgs = ["-Djavafx.cachedir=${projectDir}/.javafx-cache"]
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(25)
    }
}

shadowJar {
    archiveBaseName = "javafx-tutorial-duke"
    archiveClassifier = null
}
